name: Publish release
on:
  push:
    tags:
    - v*.*
jobs:
  publush-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install libgcrypt
      run: sudo apt-get install -y libgcrypt-dev
    - name: build
      run: make
    - name: release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            radiusplugin.so
            radiusplugin.cnf
